# Project:   dfe-archiver
# File:      clippy.toml
# Purpose:   Clippy linter configuration
#
# License:   BUSL-1.1
# Copyright: (c) 2026 HYPERI PTY LIMITED

too-many-arguments-threshold = 7
cognitive-complexity-threshold = 25
